name: Build and deploy dev

on:
  workflow_run:
    workflows:
      - "Terraform Apply on Dev environment"
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show ref
        if:  ${{ contains(fromJson('["refs/heads/develop", "refs/heads/release", "refs/heads/master"]'), github.ref) || startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: |
          echo "It's working"

      - name: Show default environment variables
        run: |
          echo "ref=`basename ${{github.ref_name}}`"
