name: Build and deploy dev

on:
  workflow_run:
    workflows:
      - "Terraform Apply on Dev environment"
    branches:
      - develop
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: List files
        shell: bash
        run: |
          echo "These are the files"
          ls -latr
      
