name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions:  read   

jobs:
  release:
    name: release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          semantic_version: 22.0.7
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
            @semantic-release/github@9.2.2
            @semantic-release/exec@6.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master -> release
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: master
          target_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge release -> develop
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: release
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
