name: 'Terraform Apply on Staging environment'
 
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Run terraform apply on staging
        shell: bash
        run: |
          echo "Run terraform apply on staging"