name: Terraform Apply on Dev environment

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:

jobs:
  terraform-apply:
#    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Run terraform apply on dev
        shell: bash
        run: |
          echo "Run terraform apply on dev"
          
