name: 'Terraform Apply on Staging environment'
 
on:
  pull_request:
    branches:
      - release
    types:
      - closed
  workflow_dispatch:

jobs:
  terraform-apply:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Run terraform apply on staging
        shell: bash
        run: |
          echo "Run terraform apply on staging"