name: 'Terraform Plan on Staging environment'
 
on:
  pull_request:
    branches:
      - release
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Run terraform plan on staging
        shell: bash
        run: |
          echo "Run terraform plan on staging"