name: test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:3.1-alpine
      options: --entrypoint /bin/bash
    services:
      sql:
        image: mcr.microsoft.com/azure-sql-edge:latest     
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: test
        ports:
          - 1433:1433
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Install SQL Server Client Tools
        run: |
          apk add --no-cache sudo
          sudo apk add --no-cache curl
          curl -o /tmp/mssql.asc https://packages.microsoft.com/keys/microsoft.asc
          sudo mv /tmp/mssql.asc /etc/apk/keys/mssql.asc
          echo "https://packages.microsoft.com/alpine/3.9/mssql-server-2019" | sudo tee -a /etc/apk/repositories
          sudo apk update
          sudo apk add mssql-tools unixodbc-dev

      - name: Test SQL Server Connection
        run: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P test -Q "SELECT @@VERSION"        


