name: Validate searchExport

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:3.1-alpine
      options: --entrypoint /bin/bash
    services:
      redis:
        image: mcr.microsoft.com/azure-sql-edge:latest     
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: test
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Install dev tools"
        run: |
          ls -latr
          dotnet tool restore
      - name: "Run dotnet format"
        run: dotnet format --check